version: 2

models:
  - name: stg_house_sales
    columns:
      - name: property_sale_id
        tests: [not_null]
      - name: sale_date
        tests: [not_null]
      - name: price
        tests:
          - not_null
      - name: bedrooms
        tests:
          - not_null
