select
    cast(id as bigint)                                     as property_sale_id,
    to_date(left(date, 8), 'YYYYMMDD')                     as sale_date,
    cast(try_to_double(price) as number(12, 2))            as price,
    try_to_number(bedrooms)                                as bedrooms,
    try_to_double(bathrooms)                               as bathrooms,
    try_to_number(sqft_living)                             as sqft_living,
    try_to_number(sqft_lot)                                as sqft_lot,
    try_to_double(floors)                                  as floors,
    try_to_number(waterfront) = 1                          as is_waterfront,
    try_to_number(view)                                    as view_score,
    try_to_number(condition)                               as condition_score,
    try_to_number(grade)                                   as grade_score,
    try_to_number(sqft_above)                              as sqft_above,
    try_to_number(sqft_basement)                           as sqft_basement,
    try_to_number(yr_built)                                as year_built,
    nullif(try_to_number(yr_renovated), 0)                 as year_renovated,
    zipcode,
    try_to_double(lat)                                     as latitude,
    try_to_double(long)                                    as longitude,
    try_to_number(sqft_living15)                           as sqft_living_neighbors,
    try_to_number(sqft_lot15)                              as sqft_lot_neighbors,
    _loaded_at,
    _source_file
from {{ source('raw', 'raw_house_sales') }}
